// Unit tests for js/carnet.js + js/store.js. Run: node tools/test-carnet.mjs
import * as C from '../js/carnet.js';
import * as St from '../js/store.js';
let fail = 0; const ok = (c, m) => { console.log((c ? 'PASS ' : 'FAIL ') + m); if (!c) fail++; };
const it = (o) => St.sanitizeItem(o);
const a = it({ id: 'a', name: 'Show laptop A', make: 'Apple', model: 'MacBook Pro 16"', serial: 'X1', price: 3499, origin: 'China', weight: 2.14, weightUnit: 'kg' });
const b = it({ id: 'b', name: 'Shure SLXD24 receiver', make: 'Shure', model: 'SLXD4', serial: 'S1, S2', qty: 2, price: 500, currentValue: 400, origin: 'Mexico', weight: 2, weightUnit: 'lb' });
const c = it({ id: 'c', name: 'Gaff tape', price: null, origin: '', serial: '' });
ok(C.tradeDescription(a) === 'Apple MacBook Pro 16" – Show laptop A', 'trade description joins make/model/name: ' + C.tradeDescription(a));
ok(C.tradeDescription(it({ name: 'Apple Mac Studio M2', make: 'Apple', model: 'Mac Studio' })) === 'Apple Mac Studio M2', 'no duplicate when name contains make+model');
ok(C.tradeDescription(a, true).endsWith('(S/N X1)'), 'serial-in-description option');
const S = { items: [a, b, c], kits: [{ id: 'k1', name: 'Rack A', itemIds: ['b', 'a'] }], trips: [] };
const trip = { ...St.makeTrip(), kitIds: ['k1'], itemIds: ['a', 'c'], currency: 'USD', weightUnit: 'kg' };
const gl = C.buildGeneralList(S, trip);
ok(gl.lines.map(l => l.itemId).join() === 'b,a,c', 'kit order then extra items, deduped: ' + gl.lines.map(l => l.itemId).join());
ok(gl.lines[0].value === 800 && gl.lines[0].usesCurrent, 'current value overrides price and multiplies by pieces (2×400)');
ok(Math.abs(gl.lines[0].weight - 1.81) < 0.01, '2×2 lb → 1.81 kg: ' + gl.lines[0].weight);
ok(gl.totals.pieces === 4 && gl.totals.value === 4299, 'totals pieces 4 value 4299: ' + JSON.stringify(gl.totals));
ok(gl.totals.errors === 1 && gl.counts.serial === 1 && gl.counts.origin === 1 && gl.counts.value === 1, 'missing serial/value/origin flagged on gaff tape');
const gl2 = C.buildGeneralList(S, { ...trip, excluded: ['c'], weightUnit: 'lb' });
ok(gl2.lines.length === 2 && gl2.totals.errors === 0, 'excluded item dropped');
ok(Math.abs(gl2.lines[1].weight - 4.72) < 0.01, '2.14 kg → 4.72 lb');
const eur = it({ ...a, id: 'e', currency: 'EUR' });
ok(C.itemIssues(eur, 'USD').some(x => x.k === 'currency'), 'currency mismatch flagged');
const csv = C.generalListCSV(gl, { ...trip, name: 'Test, "quoted"' });
ok(csv.startsWith('\uFEFF') && csv.includes('\r\n') && csv.includes('"Test, ""quoted"""'), 'CSV has BOM, CRLF, quoting');
const back = C.parseCSV(csv);
ok(back.some(r => r[0] === '1' && r[1] === 'Shure SLXD4 – Shure SLXD24 receiver' && r[2] === 'S1, S2'), 'CSV round-trips a line');
const inv = C.inventoryCSV([a, b]);
const parsed = C.parseInventoryCSV(inv);
ok(parsed.length === 2 && parsed[0].model === 'MacBook Pro 16"' && parsed[1].tags === '' && parsed[1].currentValue === '400', 'inventory CSV round trip');
const alias = C.parseInventoryCSV('Description,Brand,Serial Number,Price,Country of Origin\nRouter,Ubiquiti,U123,199.99,China\n');
ok(alias[0].name === 'Router' && alias[0].make === 'Ubiquiti' && alias[0].serial === 'U123' && alias[0].origin === 'China', 'CSV header aliases');
ok(St.sanitizeItem({ price: '$1,299.50', qty: '0', tags: 'a; b, a' }).price === 1299.5, 'price parsing strips $ and commas');
ok(St.sanitizeItem({ qty: '0' }).qty === 1 && St.sanitizeItem({ tags: 'a; b, a' }).tags.join() === 'a,b', 'qty min 1, tags dedupe');
let threw = false; try { St.sanitizeState({}); } catch { threw = true; } ok(threw, 'rejects non-backup JSON');
console.log(fail ? `${fail} FAILED` : 'ALL PASS'); process.exit(fail ? 1 : 0);
